variable project_name {}
variable aws_region {}
variable vpc_cidr {}
variable pub_sub_nat_1 {}
variable pub_sub_nat_2 {} 
variable priv_sub_web_1 {}
variable priv_sub_web_2 {}
variable priv_sub_db_1 {}
variable priv_sub_db_2 {}
variable db_username {}
variable db_password {}
variable certificate_domain_name {}
variable additional_domain_name {}
