variable project_name {}
variable region {}
variable vpc_cidr {}
variable public_sub_1a {}
variable public_sub_2b {} 
variable private_sub_3a {}
variable private_sub_4b {}
variable private_sub_5a {}
variable private_sub_6b {}
variable db_username {}
variable db_password {}
variable certificate_domain_name {}
variable additional_domain_name {}
